### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by venkivijay** [svivoli/Studio-By-Bobo#2]
Hey @svivoli, I came across your repo today when I was searching for a good portfolio specially curated for artists. I can see that you are actively building this awesome thing and I am wondering if we could collaborate in building this.

Thanks.

**Comment by svivoli** [comment]
Hi @venkivijay, thanks for your message! Are you wondering if we can collaborate on your own portfolio or the project I'm currently working on?

Sarah

**Comment by venkivijay** [comment]
On your project that you are currently working on (Studio-By-Bobo)

Thanks
Venki

**Comment by venkivijay** [comment]
@svivoli Closing this issue as there is no reply. Thanks
